grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      C : 1000
      max_iter :  500
      multi_class :  'auto'
      penalty :  'l2'
      solver :  'lbfgs'
    search_param_grid:
      C:
      - 1000
      max_iter : 
      - 113
      multi_class:
      -  'auto'
      penalty :
      - 'l2'
      solver:
      - 'lbfgs'
