FROM python:3.8.5-slim-buster

WORKDIR /app

COPY . /app

ARG AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY

ARG AWS_DEFAULT_REGION

ARG MONGO_DB_URL 

ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID

ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY

ENV AWS_DEFAULT_REGION $AWS_DEFAULT_REGION

ENV MONGO_DB_URL $MONGO_DB_URL

RUN pip install -r requirements.txt

CMD ["python3", "app.py"]